"""empty message

Revision ID: 3f243b7a2838
Revises: dcc49bffccc
Create Date: 2016-05-01 09:33:00.994110

"""

# revision identifiers, used by Alembic.
revision = '3f243b7a2838'
down_revision = 'dcc49bffccc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ESBLightState',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Unicode(length=255), server_default=u'', nullable=True),
    sa.Column('tweet', sa.Unicode(length=255), server_default=u'', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ESBLightState')
    ### end Alembic commands ###
