"""empty message

Revision ID: 598671455b6e
Revises: 76bf6c80dfd
Create Date: 2016-05-07 23:05:41.897561

"""

# revision identifiers, used by Alembic.
revision = '598671455b6e'
down_revision = '76bf6c80dfd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ESBLightState', sa.Column('tweeted', sa.Boolean(), server_default=u'false', nullable=True))
    op.create_unique_constraint(None, 'ESBLightState', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ESBLightState', type_='unique')
    op.drop_column('ESBLightState', 'tweeted')
    ### end Alembic commands ###
