"""empty message

Revision ID: dcc49bffccc
Revises: None
Create Date: 2016-04-24 18:01:18.148899

"""

# revision identifiers, used by Alembic.
revision = 'dcc49bffccc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ESBLightState',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Unicode(length=255), server_default=u'', nullable=True),
    sa.Column('color', sa.Unicode(length=255), server_default=u'', nullable=True),
    sa.Column('pic_link', sa.Unicode(length=255), server_default=u'', nullable=True),
    sa.Column('strange_description', sa.Unicode(length=255), server_default=u'', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ESBLightState')
    ### end Alembic commands ###
